<?php

namespace App\Services\Optimization\Helpers;

/**
 * Optimizasyon algoritmaları için Python ve MATLAB kod üretici
 */
class CodeGenerator
{
    /**
     * Python kodu üret (NumPy ile)
     */
    public static function generatePython(
        string $algorithm,
        int $populationSize,
        int $maxIterations,
        int $dimension,
        float $lowerBound,
        float $upperBound,
        string $objectiveFunction = 'sphere',
        ?string $customExpression = null
    ): string {
        $objFuncCode = self::getPythonObjectiveFunction($objectiveFunction, $customExpression);
        
        if ($algorithm === 'woa') {
            return self::generatePythonWOA($populationSize, $maxIterations, $dimension, $lowerBound, $upperBound, $objFuncCode);
        } else {
            return self::generatePythonPSO($populationSize, $maxIterations, $dimension, $lowerBound, $upperBound, $objFuncCode);
        }
    }

    /**
     * MATLAB kodu üret
     */
    public static function generateMatlab(
        string $algorithm,
        int $populationSize,
        int $maxIterations,
        int $dimension,
        float $lowerBound,
        float $upperBound,
        string $objectiveFunction = 'sphere',
        ?string $customExpression = null
    ): string {
        $objFuncCode = self::getMatlabObjectiveFunction($objectiveFunction, $customExpression);
        
        if ($algorithm === 'woa') {
            return self::generateMatlabWOA($populationSize, $maxIterations, $dimension, $lowerBound, $upperBound, $objFuncCode);
        } else {
            return self::generateMatlabPSO($populationSize, $maxIterations, $dimension, $lowerBound, $upperBound, $objFuncCode);
        }
    }

    /**
     * Python WOA kodu
     */
    private static function generatePythonWOA(int $pop, int $maxIter, int $dim, float $lb, float $ub, string $objFunc): string
    {
        return <<<PYTHON
import numpy as np
import matplotlib.pyplot as plt

# =================================================================
# Whale Optimization Algorithm (WOA)
# Mirjalili & Lewis, 2016
# Generated by balina.alienes.me
# =================================================================

{$objFunc}

def WOA(obj_func, dim, pop_size, max_iter, lb, ub):
    \"\"\"
    Whale Optimization Algorithm
    
    Parameters:
    -----------
    obj_func : callable - Objective function to minimize
    dim : int - Number of dimensions
    pop_size : int - Population size
    max_iter : int - Maximum iterations
    lb, ub : float - Lower and upper bounds
    
    Returns:
    --------
    best_pos : array - Best solution found
    best_fitness : float - Best fitness value
    convergence : list - Convergence history
    \"\"\"
    
    # Initialize population
    positions = np.random.uniform(lb, ub, (pop_size, dim))
    fitness = np.array([obj_func(pos) for pos in positions])
    
    # Find initial best
    best_idx = np.argmin(fitness)
    best_pos = positions[best_idx].copy()
    best_fitness = fitness[best_idx]
    
    convergence = [best_fitness]
    
    for t in range(max_iter):
        # Linearly decrease from 2 to 0
        a = 2 - t * (2 / max_iter)
        a2 = -1 + t * (-1 / max_iter)
        
        for i in range(pop_size):
            r1 = np.random.random()
            r2 = np.random.random()
            
            A = 2 * a * r1 - a
            C = 2 * r2
            
            b = 1
            l = (a2 - 1) * np.random.random() + 1
            
            p = np.random.random()
            
            if p < 0.5:
                if abs(A) < 1:
                    # Encircling prey (Exploitation)
                    D = abs(C * best_pos - positions[i])
                    positions[i] = best_pos - A * D
                else:
                    # Search for prey (Exploration)
                    rand_idx = np.random.randint(pop_size)
                    X_rand = positions[rand_idx]
                    D = abs(C * X_rand - positions[i])
                    positions[i] = X_rand - A * D
            else:
                # Spiral update (Bubble-net attacking)
                D = abs(best_pos - positions[i])
                positions[i] = D * np.exp(b * l) * np.cos(2 * np.pi * l) + best_pos
            
            # Boundary check
            positions[i] = np.clip(positions[i], lb, ub)
            
            # Evaluate
            new_fitness = obj_func(positions[i])
            fitness[i] = new_fitness
            
            if new_fitness < best_fitness:
                best_fitness = new_fitness
                best_pos = positions[i].copy()
        
        convergence.append(best_fitness)
        print(f"Iteration {t+1}/{max_iter}, Best Fitness: {best_fitness:.6e}")
    
    return best_pos, best_fitness, convergence


# ==================== MAIN ====================
if __name__ == "__main__":
    # Parameters
    dim = {$dim}
    pop_size = {$pop}
    max_iter = {$maxIter}
    lb = {$lb}
    ub = {$ub}
    
    # Run WOA
    best_pos, best_fitness, convergence = WOA(
        objective_function, dim, pop_size, max_iter, lb, ub
    )
    
    print("\\n" + "="*50)
    print("OPTIMIZATION RESULTS")
    print("="*50)
    print(f"Best Position: {best_pos}")
    print(f"Best Fitness: {best_fitness:.10e}")
    
    # Plot convergence curve
    plt.figure(figsize=(10, 6))
    plt.plot(convergence, 'b-', linewidth=2)
    plt.xlabel('Iteration')
    plt.ylabel('Best Fitness')
    plt.title('WOA Convergence Curve')
    plt.grid(True, alpha=0.3)
    plt.yscale('log')
    plt.tight_layout()
    plt.savefig('woa_convergence.png', dpi=150)
    plt.show()
PYTHON;
    }

    /**
     * Python PSO kodu
     */
    private static function generatePythonPSO(int $pop, int $maxIter, int $dim, float $lb, float $ub, string $objFunc): string
    {
        return <<<PYTHON
import numpy as np
import matplotlib.pyplot as plt

# =================================================================
# Particle Swarm Optimization (PSO)
# Kennedy & Eberhart, 1995
# Generated by balina.alienes.me
# =================================================================

{$objFunc}

def PSO(obj_func, dim, pop_size, max_iter, lb, ub, w=0.7, c1=2.0, c2=2.0):
    \"\"\"
    Particle Swarm Optimization
    
    Parameters:
    -----------
    obj_func : callable - Objective function to minimize
    dim : int - Number of dimensions
    pop_size : int - Number of particles
    max_iter : int - Maximum iterations
    lb, ub : float - Lower and upper bounds
    w : float - Inertia weight
    c1 : float - Cognitive coefficient
    c2 : float - Social coefficient
    
    Returns:
    --------
    gbest_pos : array - Global best position
    gbest_fitness : float - Global best fitness
    convergence : list - Convergence history
    \"\"\"
    
    # Initialize particles
    positions = np.random.uniform(lb, ub, (pop_size, dim))
    velocities = np.random.uniform(-(ub-lb)/2, (ub-lb)/2, (pop_size, dim))
    
    # Evaluate initial fitness
    fitness = np.array([obj_func(pos) for pos in positions])
    
    # Initialize personal best
    pbest_pos = positions.copy()
    pbest_fitness = fitness.copy()
    
    # Initialize global best
    gbest_idx = np.argmin(fitness)
    gbest_pos = positions[gbest_idx].copy()
    gbest_fitness = fitness[gbest_idx]
    
    convergence = [gbest_fitness]
    
    for t in range(max_iter):
        for i in range(pop_size):
            r1 = np.random.random(dim)
            r2 = np.random.random(dim)
            
            # Update velocity
            velocities[i] = (w * velocities[i] + 
                           c1 * r1 * (pbest_pos[i] - positions[i]) +
                           c2 * r2 * (gbest_pos - positions[i]))
            
            # Update position
            positions[i] = positions[i] + velocities[i]
            
            # Boundary check
            positions[i] = np.clip(positions[i], lb, ub)
            
            # Evaluate
            new_fitness = obj_func(positions[i])
            fitness[i] = new_fitness
            
            # Update personal best
            if new_fitness < pbest_fitness[i]:
                pbest_fitness[i] = new_fitness
                pbest_pos[i] = positions[i].copy()
                
                # Update global best
                if new_fitness < gbest_fitness:
                    gbest_fitness = new_fitness
                    gbest_pos = positions[i].copy()
        
        convergence.append(gbest_fitness)
        print(f"Iteration {t+1}/{max_iter}, Best Fitness: {gbest_fitness:.6e}")
    
    return gbest_pos, gbest_fitness, convergence


# ==================== MAIN ====================
if __name__ == "__main__":
    # Parameters
    dim = {$dim}
    pop_size = {$pop}
    max_iter = {$maxIter}
    lb = {$lb}
    ub = {$ub}
    
    # PSO Parameters
    w = 0.7    # Inertia weight
    c1 = 2.0   # Cognitive coefficient
    c2 = 2.0   # Social coefficient
    
    # Run PSO
    gbest_pos, gbest_fitness, convergence = PSO(
        objective_function, dim, pop_size, max_iter, lb, ub, w, c1, c2
    )
    
    print("\\n" + "="*50)
    print("OPTIMIZATION RESULTS")
    print("="*50)
    print(f"Global Best Position: {gbest_pos}")
    print(f"Global Best Fitness: {gbest_fitness:.10e}")
    
    # Plot convergence curve
    plt.figure(figsize=(10, 6))
    plt.plot(convergence, 'r-', linewidth=2)
    plt.xlabel('Iteration')
    plt.ylabel('Best Fitness')
    plt.title('PSO Convergence Curve')
    plt.grid(True, alpha=0.3)
    plt.yscale('log')
    plt.tight_layout()
    plt.savefig('pso_convergence.png', dpi=150)
    plt.show()
PYTHON;
    }

    /**
     * MATLAB WOA kodu
     */
    private static function generateMatlabWOA(int $pop, int $maxIter, int $dim, float $lb, float $ub, string $objFunc): string
    {
        return <<<MATLAB
%% =================================================================
%% Whale Optimization Algorithm (WOA)
%% Mirjalili & Lewis, 2016
%% Generated by balina.alienes.me
%% =================================================================

clear; clc; close all;

%% Parameters
dim = {$dim};
pop_size = {$pop};
max_iter = {$maxIter};
lb = {$lb};
ub = {$ub};

%% Objective Function
{$objFunc}

%% Initialize Population
positions = lb + (ub - lb) * rand(pop_size, dim);
fitness = zeros(pop_size, 1);

for i = 1:pop_size
    fitness(i) = obj_func(positions(i, :));
end

%% Find Initial Best
[best_fitness, best_idx] = min(fitness);
best_pos = positions(best_idx, :);

convergence = zeros(max_iter + 1, 1);
convergence(1) = best_fitness;

%% Main Loop
for t = 1:max_iter
    % Linearly decrease from 2 to 0
    a = 2 - t * (2 / max_iter);
    a2 = -1 + t * (-1 / max_iter);
    
    for i = 1:pop_size
        r1 = rand();
        r2 = rand();
        
        A = 2 * a * r1 - a;
        C = 2 * r2;
        
        b = 1;
        l = (a2 - 1) * rand() + 1;
        
        p = rand();
        
        if p < 0.5
            if abs(A) < 1
                % Encircling prey (Exploitation)
                D = abs(C * best_pos - positions(i, :));
                positions(i, :) = best_pos - A * D;
            else
                % Search for prey (Exploration)
                rand_idx = randi(pop_size);
                X_rand = positions(rand_idx, :);
                D = abs(C * X_rand - positions(i, :));
                positions(i, :) = X_rand - A * D;
            end
        else
            % Spiral update (Bubble-net attacking)
            D = abs(best_pos - positions(i, :));
            positions(i, :) = D .* exp(b * l) .* cos(2 * pi * l) + best_pos;
        end
        
        % Boundary check
        positions(i, :) = max(positions(i, :), lb);
        positions(i, :) = min(positions(i, :), ub);
        
        % Evaluate
        fitness(i) = obj_func(positions(i, :));
        
        if fitness(i) < best_fitness
            best_fitness = fitness(i);
            best_pos = positions(i, :);
        end
    end
    
    convergence(t + 1) = best_fitness;
    fprintf('Iteration %d/%d, Best Fitness: %.6e\\n', t, max_iter, best_fitness);
end

%% Results
fprintf('\\n==================================================\\n');
fprintf('OPTIMIZATION RESULTS\\n');
fprintf('==================================================\\n');
fprintf('Best Position: ');
disp(best_pos);
fprintf('Best Fitness: %.10e\\n', best_fitness);

%% Plot Convergence Curve
figure('Position', [100, 100, 800, 500]);
semilogy(0:max_iter, convergence, 'b-', 'LineWidth', 2);
xlabel('Iteration');
ylabel('Best Fitness');
title('WOA Convergence Curve');
grid on;
saveas(gcf, 'woa_convergence.png');
MATLAB;
    }

    /**
     * MATLAB PSO kodu
     */
    private static function generateMatlabPSO(int $pop, int $maxIter, int $dim, float $lb, float $ub, string $objFunc): string
    {
        return <<<MATLAB
%% =================================================================
%% Particle Swarm Optimization (PSO)
%% Kennedy & Eberhart, 1995
%% Generated by balina.alienes.me
%% =================================================================

clear; clc; close all;

%% Parameters
dim = {$dim};
pop_size = {$pop};
max_iter = {$maxIter};
lb = {$lb};
ub = {$ub};

% PSO Parameters
w = 0.7;    % Inertia weight
c1 = 2.0;   % Cognitive coefficient
c2 = 2.0;   % Social coefficient

%% Objective Function
{$objFunc}

%% Initialize Particles
positions = lb + (ub - lb) * rand(pop_size, dim);
velocities = (ub - lb) * (rand(pop_size, dim) - 0.5);
fitness = zeros(pop_size, 1);

for i = 1:pop_size
    fitness(i) = obj_func(positions(i, :));
end

%% Initialize Personal Best
pbest_pos = positions;
pbest_fitness = fitness;

%% Initialize Global Best
[gbest_fitness, gbest_idx] = min(fitness);
gbest_pos = positions(gbest_idx, :);

convergence = zeros(max_iter + 1, 1);
convergence(1) = gbest_fitness;

%% Main Loop
for t = 1:max_iter
    for i = 1:pop_size
        r1 = rand(1, dim);
        r2 = rand(1, dim);
        
        % Update velocity
        velocities(i, :) = w * velocities(i, :) + ...
                          c1 * r1 .* (pbest_pos(i, :) - positions(i, :)) + ...
                          c2 * r2 .* (gbest_pos - positions(i, :));
        
        % Update position
        positions(i, :) = positions(i, :) + velocities(i, :);
        
        % Boundary check
        positions(i, :) = max(positions(i, :), lb);
        positions(i, :) = min(positions(i, :), ub);
        
        % Evaluate
        fitness(i) = obj_func(positions(i, :));
        
        % Update personal best
        if fitness(i) < pbest_fitness(i)
            pbest_fitness(i) = fitness(i);
            pbest_pos(i, :) = positions(i, :);
            
            % Update global best
            if fitness(i) < gbest_fitness
                gbest_fitness = fitness(i);
                gbest_pos = positions(i, :);
            end
        end
    end
    
    convergence(t + 1) = gbest_fitness;
    fprintf('Iteration %d/%d, Best Fitness: %.6e\\n', t, max_iter, gbest_fitness);
end

%% Results
fprintf('\\n==================================================\\n');
fprintf('OPTIMIZATION RESULTS\\n');
fprintf('==================================================\\n');
fprintf('Global Best Position: ');
disp(gbest_pos);
fprintf('Global Best Fitness: %.10e\\n', gbest_fitness);

%% Plot Convergence Curve
figure('Position', [100, 100, 800, 500]);
semilogy(0:max_iter, convergence, 'r-', 'LineWidth', 2);
xlabel('Iteration');
ylabel('Best Fitness');
title('PSO Convergence Curve');
grid on;
saveas(gcf, 'pso_convergence.png');
MATLAB;
    }

    /**
     * Python objective function kodu
     */
    private static function getPythonObjectiveFunction(string $type, ?string $custom = null): string
    {
        if ($custom) {
            $pythonExpr = self::convertToPython($custom);
            return "def objective_function(x):\n    \"\"\"Custom objective function\"\"\"\n    return {$pythonExpr}";
        }

        return match ($type) {
            'sphere' => "def objective_function(x):\n    \"\"\"Sphere Function - Global minimum at origin\"\"\"\n    return np.sum(x**2)",
            'rastrigin' => "def objective_function(x):\n    \"\"\"Rastrigin Function - Highly multimodal\"\"\"\n    n = len(x)\n    return 10*n + np.sum(x**2 - 10*np.cos(2*np.pi*x))",
            'ackley' => "def objective_function(x):\n    \"\"\"Ackley Function\"\"\"\n    n = len(x)\n    sum1 = np.sum(x**2)\n    sum2 = np.sum(np.cos(2*np.pi*x))\n    return -20*np.exp(-0.2*np.sqrt(sum1/n)) - np.exp(sum2/n) + 20 + np.e",
            'rosenbrock' => "def objective_function(x):\n    \"\"\"Rosenbrock Function - Banana function\"\"\"\n    return np.sum(100*(x[1:] - x[:-1]**2)**2 + (1 - x[:-1])**2)",
            'griewank' => "def objective_function(x):\n    \"\"\"Griewank Function\"\"\"\n    n = len(x)\n    sum_sq = np.sum(x**2) / 4000\n    prod_cos = np.prod(np.cos(x / np.sqrt(np.arange(1, n+1))))\n    return sum_sq - prod_cos + 1",
            default => "def objective_function(x):\n    \"\"\"Sphere Function\"\"\"\n    return np.sum(x**2)"
        };
    }

    /**
     * MATLAB objective function kodu
     */
    private static function getMatlabObjectiveFunction(string $type, ?string $custom = null): string
    {
        if ($custom) {
            $matlabExpr = self::convertToMatlab($custom);
            return "obj_func = @(x) {$matlabExpr};";
        }

        return match ($type) {
            'sphere' => "obj_func = @(x) sum(x.^2);",
            'rastrigin' => "obj_func = @(x) 10*length(x) + sum(x.^2 - 10*cos(2*pi*x));",
            'ackley' => "obj_func = @(x) -20*exp(-0.2*sqrt(sum(x.^2)/length(x))) - exp(sum(cos(2*pi*x))/length(x)) + 20 + exp(1);",
            'rosenbrock' => "obj_func = @(x) sum(100*(x(2:end) - x(1:end-1).^2).^2 + (1 - x(1:end-1)).^2);",
            'griewank' => "obj_func = @(x) sum(x.^2)/4000 - prod(cos(x ./ sqrt(1:length(x)))) + 1;",
            default => "obj_func = @(x) sum(x.^2);"
        };
    }

    /**
     * İfadeyi Python'a çevir
     */
    private static function convertToPython(string $expr): string
    {
        $expr = strtolower(trim($expr));
        $expr = str_replace('^', '**', $expr);
        $expr = preg_replace('/\bpi\b/', 'np.pi', $expr);
        $expr = preg_replace('/\bsin\(/', 'np.sin(', $expr);
        $expr = preg_replace('/\bcos\(/', 'np.cos(', $expr);
        $expr = preg_replace('/\btan\(/', 'np.tan(', $expr);
        $expr = preg_replace('/\bsqrt\(/', 'np.sqrt(', $expr);
        $expr = preg_replace('/\bexp\(/', 'np.exp(', $expr);
        $expr = preg_replace('/\blogs\(/', 'np.log(', $expr);
        $expr = preg_replace('/\babs\(/', 'np.abs(', $expr);
        
        // x, y -> x[0], x[1]
        $expr = preg_replace('/(?<![a-z])x(?![a-z0-9\[])/', 'x[0]', $expr);
        $expr = preg_replace('/(?<![a-z])y(?![a-z0-9\[])/', 'x[1]', $expr);
        $expr = preg_replace('/(?<![a-z])z(?![a-z0-9\[])/', 'x[2]', $expr);
        
        return $expr;
    }

    /**
     * İfadeyi MATLAB'e çevir
     */
    private static function convertToMatlab(string $expr): string
    {
        $expr = strtolower(trim($expr));
        // Element-wise operations
        $expr = str_replace('^', '.^', $expr);
        $expr = str_replace('*', '.*', $expr);
        $expr = str_replace('/', './', $expr);
        
        // x, y -> x(1), x(2)
        $expr = preg_replace('/(?<![a-z])x(?![a-z0-9\(])/', 'x(1)', $expr);
        $expr = preg_replace('/(?<![a-z])y(?![a-z0-9\(])/', 'x(2)', $expr);
        $expr = preg_replace('/(?<![a-z])z(?![a-z0-9\(])/', 'x(3)', $expr);
        
        return $expr;
    }
}
